# Generated by Django 5.2.3 on 2025-07-03 07:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CodigoQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=100, unique=True)),
                ("imagen_qr", models.ImageField(upload_to="codigos_qr/")),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Código QR",
                "verbose_name_plural": "Códigos QR",
            },
        ),
        migrations.CreateModel(
            name="Deporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoCampeonato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tipo de Campeonato",
                "verbose_name_plural": "Tipos de Campeonato",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("DELEGADO", "Delegado de Carrera"),
                            ("JUGADOR", "Jugador"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "carrera",
                    models.CharField(
                        choices=[
                            ("Tics", "Tics"),
                            ("Derecho", "Derecho"),
                            ("Medicina", "Medicina"),
                            ("Arquitectura", "Arquitectura"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="usuarios_custom",
                        related_query_name="usuario_custom",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="usuarios_custom",
                        related_query_name="usuario_custom",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Campeonato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField()),
                (
                    "reglamento",
                    models.FileField(blank=True, null=True, upload_to="reglamentos/"),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INSCRIPCION", "Inscripción Abierta"),
                            ("CERRADO", "Inscripción Cerrada"),
                            ("EN_CURSO", "En Curso"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="INSCRIPCION",
                        max_length=20,
                    ),
                ),
                (
                    "dias_partido",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("LUNES", "Lunes"),
                            ("MARTES", "Martes"),
                            ("MIERCOLES", "Miércoles"),
                            ("JUEVES", "Jueves"),
                            ("VIERNES", "Viernes"),
                            ("SABADO", "Sábado"),
                            ("DOMINGO", "Domingo"),
                        ],
                        default=[],
                        max_length=52,
                    ),
                ),
                (
                    "max_jugadores_por_equipo",
                    models.PositiveIntegerField(
                        default=11,
                        help_text="Cantidad máxima de jugadores por equipo en este campeonato",
                    ),
                ),
                (
                    "precio_inscripcion",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "delegado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campeonatos_delegado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "codigo_qr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campeonatos",
                        to="core.codigoqr",
                    ),
                ),
                (
                    "deporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campeonatos",
                        to="core.deporte",
                    ),
                ),
                (
                    "tipo_campeonato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campeonatos",
                        to="core.tipocampeonato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Arbitro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("experiencia", models.TextField()),
                ("contacto", models.CharField(max_length=100)),
                ("estado", models.BooleanField(default=True)),
                (
                    "deportes",
                    models.ManyToManyField(related_name="arbitros", to="core.deporte"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="logos_equipos/")),
                ("aprobado", models.BooleanField(default=False)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos",
                        to="core.campeonato",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos",
                        to="core.carrera",
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        limit_choices_to={"rol": "DELEGADO"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_camiseta", models.PositiveIntegerField()),
                ("edad", models.PositiveIntegerField()),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugadores",
                        to="core.equipo",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"rol": "JUGADOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("equipo", "numero_camiseta")},
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("EFECTIVO", "Efectivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "comprobante_pago",
                    models.ImageField(blank=True, null=True, upload_to="comprobantes/"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("observacion_admin", models.TextField(blank=True, null=True)),
                (
                    "codigo_qr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.codigoqr",
                    ),
                ),
                (
                    "equipo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="core.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("lugar", models.CharField(max_length=100)),
                ("resultado_local", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "resultado_visitante",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADO", "Programado"),
                            ("EN_CURSO", "En Curso"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="PROGRAMADO",
                        max_length=20,
                    ),
                ),
                (
                    "arbitro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.arbitro",
                    ),
                ),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos",
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_locales",
                        to="core.equipo",
                    ),
                ),
                (
                    "equipo_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_visitantes",
                        to="core.equipo",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("campeonato", "fecha", "hora", "equipo_local", "equipo_visitante")
                },
            },
        ),
        migrations.CreateModel(
            name="Suspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("motivo", models.TextField()),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensiones",
                        to="core.jugador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticaJugadorVideojuegos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidas_jugadas", models.PositiveIntegerField(default=0)),
                ("partidas_ganadas", models.PositiveIntegerField(default=0)),
                ("partidas_perdidas", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jugador"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaJugadorTenis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("sets_ganados", models.PositiveIntegerField(default=0)),
                ("sets_perdidos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jugador"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaJugadorPingPong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("partidos_ganados", models.PositiveIntegerField(default=0)),
                ("partidos_perdidos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jugador"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaJugadorFutbolin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("partidos_ganados", models.PositiveIntegerField(default=0)),
                ("partidos_perdidos", models.PositiveIntegerField(default=0)),
                ("goles", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jugador"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaJugadorFutbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("goles", models.PositiveIntegerField(default=0)),
                ("tarjetas_amarillas", models.PositiveIntegerField(default=0)),
                ("tarjetas_rojas", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jugador"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaJugadorEcuaboly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("sets_ganados", models.PositiveIntegerField(default=0)),
                ("sets_perdidos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jugador"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaJugadorBasquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("canastas", models.PositiveIntegerField(default=0)),
                ("rebotes", models.PositiveIntegerField(default=0)),
                ("asistencias", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jugador"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaJugadorAjedrez",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidas_jugadas", models.PositiveIntegerField(default=0)),
                ("partidas_ganadas", models.PositiveIntegerField(default=0)),
                ("partidas_empatadas", models.PositiveIntegerField(default=0)),
                ("partidas_perdidas", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.jugador"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="Transmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enlace", models.URLField()),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmisiones",
                        to="core.campeonato",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmision",
                        to="core.partido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transmisión",
                "verbose_name_plural": "Transmisiones",
                "unique_together": {("campeonato", "partido")},
            },
        ),
    ]
