# Generated by Django 5.2.3 on 2025-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("DELEGADO", "Delegado de Carrera"),
                    ("JUGADOR", "Jugador"),
                ],
                default="JUGADOR",
                max_length=20,
            ),
        ),
    ]
