# Generated by Django 5.2.3 on 2025-06-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=100, unique=True)),
                ("imagen_qr", models.ImageField(upload_to="codigos_qr/")),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Código QR",
                "verbose_name_plural": "Códigos QR",
            },
        ),
        migrations.AddField(
            model_name="campeonato",
            name="precio_inscripcion",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="partido",
            name="resultado_local",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="partido",
            name="resultado_visitante",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("EFECTIVO", "Efectivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "comprobante_pago",
                    models.ImageField(blank=True, null=True, upload_to="comprobantes/"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("observacion_admin", models.TextField(blank=True, null=True)),
                (
                    "codigo_qr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.codigoqr",
                    ),
                ),
                (
                    "equipo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="core.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "unique_together": {("equipo", "metodo")},
            },
        ),
        migrations.CreateModel(
            name="Transmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enlace", models.URLField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmisiones",
                        to="core.campeonato",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmision",
                        to="core.partido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transmisión",
                "verbose_name_plural": "Transmisiones",
                "unique_together": {("campeonato", "partido")},
            },
        ),
    ]
