# Generated by Django 5.2.3 on 2025-08-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codigoqr",
            options={
                "ordering": ["-es_principal", "banco", "numero_cuenta"],
                "verbose_name": "Código QR",
                "verbose_name_plural": "Códigos QR",
            },
        ),
        migrations.AlterModelOptions(
            name="pago",
            options={
                "ordering": ["-fecha_pago"],
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.AddField(
            model_name="codigoqr",
            name="activo",
            field=models.BooleanField(
                default=True, help_text="Si está activo, se muestra a los delegados."
            ),
        ),
        migrations.AddField(
            model_name="codigoqr",
            name="es_principal",
            field=models.BooleanField(
                default=False, help_text="Si está marcado, se usa por defecto."
            ),
        ),
        migrations.AlterField(
            model_name="codigoqr",
            name="banco",
            field=models.CharField(max_length=100, verbose_name="Nombre del banco"),
        ),
        migrations.AlterField(
            model_name="pago",
            name="codigo_qr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos",
                to="core.codigoqr",
            ),
        ),
        migrations.AddConstraint(
            model_name="codigoqr",
            constraint=models.UniqueConstraint(
                fields=("banco", "numero_cuenta"), name="uniq_banco_numero_cuenta"
            ),
        ),
    ]
