# Generated by Django 5.2.3 on 2025-08-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipocampeonato",
            name="deportes_permitidos",
            field=models.ManyToManyField(
                related_name="tipos_permitidos", to="core.deporte"
            ),
        ),
    ]
