# Generated by Django 5.2.3 on 2025-08-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="observaciones_arbitro",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="suspensiones_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="tarjetas_amarillas_local",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="tarjetas_amarillas_visitante",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="tarjetas_rojas_local",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="tarjetas_rojas_visitante",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
