# Generated by Django 5.2.3 on 2025-08-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_jugador_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="campeonato",
            name="fecha_fin_inscripcion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campeonato",
            name="fixture_generado",
            field=models.BooleanField(default=False),
        ),
    ]
