# Generated by Django 5.2.3 on 2025-09-21 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_codigoqr_options_alter_pago_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pago",
            options={"verbose_name": "Pago", "verbose_name_plural": "Pagos"},
        ),
        migrations.RenameField(
            model_name="estadisticajugadorajedrez",
            old_name="partidas_jugadas",
            new_name="partidos_jugados",
        ),
        migrations.RenameField(
            model_name="estadisticajugadorvideojuegos",
            old_name="partidas_jugadas",
            new_name="partidos_jugados",
        ),
        migrations.RenameField(
            model_name="imagengaleria",
            old_name="fecha",
            new_name="creado_en",
        ),
        migrations.RenameField(
            model_name="noticia",
            old_name="fecha_publicacion",
            new_name="creado_en",
        ),
        migrations.RenameField(
            model_name="testimonio",
            old_name="fecha",
            new_name="creado_en",
        ),
        migrations.AddField(
            model_name="imagengaleria",
            name="actualizado_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="noticia",
            name="actualizado_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="testimonio",
            name="actualizado_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="campeonato",
            name="max_jugadores_por_equipo",
            field=models.PositiveIntegerField(
                default=11, help_text="Cantidad máxima de jugadores por equipo"
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="codigo_qr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.codigoqr",
            ),
        ),
    ]
