# Generated by Django 5.2.3 on 2025-07-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_usuario_rol"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenGaleria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="galeria/")),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="noticias/"),
                ),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="testimonios/"),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
