# Generated by Django 5.2.3 on 2025-08-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tipocampeonato_deportes_permitidos"),
    ]

    operations = [
        migrations.AddField(
            model_name="campeonato",
            name="arbitros_asignables",
            field=models.ManyToManyField(
                blank=True, related_name="campeonatos_asignados", to="core.arbitro"
            ),
        ),
    ]
