# Generated by Django 5.2.3 on 2025-06-24 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_codigoqr_campeonato_precio_inscripcion_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pago",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="jugador",
            name="canastas",
        ),
        migrations.RemoveField(
            model_name="jugador",
            name="goles",
        ),
        migrations.RemoveField(
            model_name="jugador",
            name="puntos",
        ),
        migrations.RemoveField(
            model_name="jugador",
            name="tarjetas_amarillas",
        ),
        migrations.RemoveField(
            model_name="jugador",
            name="tarjetas_rojas",
        ),
        migrations.AddField(
            model_name="campeonato",
            name="max_jugadores_por_equipo",
            field=models.PositiveIntegerField(
                default=11,
                help_text="Cantidad máxima de jugadores por equipo en este campeonato",
            ),
        ),
        migrations.AlterField(
            model_name="campeonato",
            name="delegado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campeonatos_delegado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campeonato",
            name="precio_inscripcion",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="partido",
            name="arbitro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.arbitro",
            ),
        ),
        migrations.AlterField(
            model_name="partido",
            name="resultado_local",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partido",
            name="resultado_visitante",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transmision",
            name="descripcion",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="Suspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("motivo", models.TextField()),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensiones",
                        to="core.jugador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstadisticasJugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goles", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                ("canastas", models.PositiveIntegerField(default=0)),
                ("tarjetas_amarillas", models.PositiveIntegerField(default=0)),
                ("tarjetas_rojas", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estadisticas",
                        to="core.jugador",
                    ),
                ),
            ],
            options={
                "unique_together": {("jugador", "campeonato")},
            },
        ),
    ]
