# Generated by Django 5.2.3 on 2025-08-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_equipo_uniq_equipo_por_delegado_por_campeonato"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equipo",
            name="uniq_equipo_por_delegado_por_campeonato",
        ),
    ]
