# Generated by Django 5.2.3 on 2025-07-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_imagengaleria_noticia_testimonio"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cedula",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
