# Generated by Django 5.2.3 on 2025-08-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_campeonato_arbitros_asignables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campeonato",
            name="arbitros_asignables",
        ),
        migrations.RemoveField(
            model_name="tipocampeonato",
            name="deportes_permitidos",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("DELEGADO", "Delegado de Carrera"),
                    ("ARBITRO", "Árbitro"),
                    ("JUGADOR", "Jugador"),
                ],
                default="JUGADOR",
                max_length=20,
            ),
        ),
    ]
