# Generated by Django 5.2.3 on 2025-07-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_estadisticabasquet_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campeonato",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
