# Generated by Django 5.2.3 on 2025-06-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_pago_unique_together_remove_jugador_canastas_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="estadisticasjugador",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="estadisticasjugador",
            name="campeonato",
        ),
        migrations.RemoveField(
            model_name="estadisticasjugador",
            name="jugador",
        ),
        migrations.CreateModel(
            name="EstadisticaAjedrez",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidas_jugadas", models.PositiveIntegerField(default=0)),
                ("partidas_ganadas", models.PositiveIntegerField(default=0)),
                ("partidas_empatadas", models.PositiveIntegerField(default=0)),
                ("partidas_perdidas", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.equipo"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "equipo")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaBasquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("canastas", models.PositiveIntegerField(default=0)),
                ("rebotes", models.PositiveIntegerField(default=0)),
                ("asistencias", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.equipo"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "equipo")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaEcuaboly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets_ganados", models.PositiveIntegerField(default=0)),
                ("sets_perdidos", models.PositiveIntegerField(default=0)),
                ("partidos_ganados", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.equipo"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "equipo")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaFutbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("goles", models.PositiveIntegerField(default=0)),
                ("tarjetas_amarillas", models.PositiveIntegerField(default=0)),
                ("tarjetas_rojas", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.equipo"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "equipo")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaFutbolin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_ganados", models.PositiveIntegerField(default=0)),
                ("partidos_perdidos", models.PositiveIntegerField(default=0)),
                ("goles", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.equipo"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "equipo")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaPingPong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidos_ganados", models.PositiveIntegerField(default=0)),
                ("partidos_perdidos", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.equipo"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "equipo")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaTenis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets_ganados", models.PositiveIntegerField(default=0)),
                ("sets_perdidos", models.PositiveIntegerField(default=0)),
                ("partidos_ganados", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.equipo"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "equipo")},
            },
        ),
        migrations.CreateModel(
            name="EstadisticaVideojuegos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partidas_ganadas", models.PositiveIntegerField(default=0)),
                ("partidas_perdidas", models.PositiveIntegerField(default=0)),
                ("puntos", models.PositiveIntegerField(default=0)),
                ("partidas_jugadas", models.PositiveIntegerField(default=0)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campeonato",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.equipo"
                    ),
                ),
            ],
            options={
                "unique_together": {("campeonato", "equipo")},
            },
        ),
        migrations.DeleteModel(
            name="EstadisticasCampeonato",
        ),
        migrations.DeleteModel(
            name="EstadisticasJugador",
        ),
    ]
