# Generated by Django 5.2.3 on 2025-08-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_equipo_uniq_equipo_por_delegado_por_campeonato"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="equipo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("delegado__isnull", False)),
                fields=("campeonato", "delegado"),
                name="uniq_equipo_por_delegado_por_campeonato",
            ),
        ),
    ]
