# Generated by Django 5.2.3 on 2025-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_usuario_cedula"),
    ]

    operations = [
        migrations.AddField(
            model_name="campeonato",
            name="es_publico",
            field=models.BooleanField(default=True),
        ),
    ]
