# Generated by Django 5.2.3 on 2025-08-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_usuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("DELEGADO", "Delegado de Carrera"),
                    ("ARBITRO", "Árbitro"),
                    ("JUGADOR", "Jugador"),
                ],
                default="JUGADOR",
                max_length=20,
            ),
        ),
    ]
