# Generated by Django 5.2.3 on 2025-07-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_campeonato_es_publico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campeonato",
            name="activo",
            field=models.CharField(
                choices=[("SI", "Sí"), ("NO", "No")], default="SI", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="campeonato",
            name="es_publico",
            field=models.CharField(
                choices=[("SI", "Sí"), ("NO", "No")], default="SI", max_length=2
            ),
        ),
    ]
