# Generated by Django 5.2.3 on 2026-09-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_validate_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='ronda',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
