# Generated by Django 5.2.3 on 2026-09-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ronda_de_eliminatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='penales_local',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='penales_visitante',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
