# Generated by Django 5.2.3 on 2025-08-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_usuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugador",
            name="posicion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="jugador",
            name="numero_camiseta",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
