# Generated by Django 5.2.3 on 2025-07-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_campeonato_activo_alter_campeonato_es_publico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codigoqr",
            name="banco",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nombre del banco"
            ),
        ),
        migrations.AlterField(
            model_name="codigoqr",
            name="descripcion",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción adicional"
            ),
        ),
        migrations.AlterField(
            model_name="codigoqr",
            name="imagen_qr",
            field=models.ImageField(
                upload_to="codigos_qr/", verbose_name="Imagen del QR"
            ),
        ),
    ]
