# Generated by Django 5.2.3 on 2025-07-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_codigoqr_banco_alter_codigoqr_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="carrera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.carrera",
            ),
        ),
    ]
