# Generated by Django 5.2.3 on 2025-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_jugador_posicion_alter_jugador_numero_camiseta"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="genero",
            field=models.CharField(
                choices=[("masculino", "Masculino"), ("femenino", "Femenino")],
                default="masculino",
                max_length=20,
            ),
        ),
    ]
