# Generated by Django 5.2.3 on 2025-07-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_usuario_carrera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos_equipos/"),
        ),
    ]
