from .admin_views import *
from .autenticacion_views import *
from .campeonato_views import *
from .delegado_views import *
from .estadisticas_views import *
from .inicio_views import *
from .jugador_views import *
from .partido_views import *
from .perfil_views import *
from .transmision_views import *
from .arbitro_views import *
from .suspension_views import *
from .equipo_views import *
