"""
Django settings for CampeonatosUIDE project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Initialize django-environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#
# Sólo SECRET_KEY es obligatoria; el resto tiene valores por defecto para
# que el proyecto arranque tras un clon y en CI sin preparar un .env.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "multiselectfield",
    'widget_tweaks',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Sirve los ficheros de STATIC_ROOT directamente desde Django en
    # produccion (Nginx solo hace proxy y no ve el volumen de estaticos).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CampeonatosUIDE.urls"

TEMPLATES_DIR = BASE_DIR / "core" / "templates"
TEMPLATES = [{
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [TEMPLATES_DIR],
    "APP_DIRS": True,
    "OPTIONS": {
        "context_processors": [
            "django.template.context_processors.request",
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
            "core.context_processors.menu_context",
        ]
    },
}]

WSGI_APPLICATION = "CampeonatosUIDE.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Si no hay DATABASE_URL definido se usa el SQLite del proyecto, para que
# el proyecto arranque tras un clon (y en CI) sin preparar un .env antes.
DATABASES = {
    'default': env.db('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-EC"

TIME_ZONE = "America/Guayaquil"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
# No se declara STATICFILES_DIRS: core/static/ vive dentro de la app core,
# así que AppDirectoriesFinder ya lo encuentra. Declararlo además hacía que
# collectstatic viera cada fichero dos veces ("Found another file with the
# destination path 'styles/uide.css'").
# Sin STATIC_ROOT, collectstatic aborta con ImproperlyConfigured y no se
# pueden preparar los estáticos para un despliegue.
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise: comprime y cachea los estaticos con hash en el nombre. El
# almacenamiento de media sigue en disco (lo sirve Nginx desde el bind mount).
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Sin "Manifest": no exige que cada referencia estatica exista en
    # collectstatic, asi que una plantilla con una ruta suelta no rompe el
    # build ni CI. Solo comprime.
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'core.Usuario'
LOGIN_URL = '/login/'

# Email (Gmail SMTP con App Password)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("SMTP_USER", default="")
EMAIL_HOST_PASSWORD = env("SMTP_PASS", default="")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "no-reply@uide.local"

# Reset de contraseña
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24
EMAIL_TIMEOUT = 20


CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Bound request bodies and uploads before application-level validation.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"


# ---------------------------------------------------------------------------
# Seguridad de transporte y cookies
#
# Todo esto se activa solo cuando DEBUG está desactivado: en desarrollo se
# sirve por HTTP, y forzar HTTPS o cookies "secure" dejaría la aplicación
# inaccesible en local. Cada valor puede forzarse por variable de entorno si
# el despliegue concreto lo necesita.
# ---------------------------------------------------------------------------

EN_PRODUCCION = not DEBUG

# El proyecto se expone detrás de un proxy (ver CSRF_TRUSTED_ORIGINS con
# *.trycloudflare.com). Sin esta cabecera Django no sabe que la petición
# original llegó por HTTPS y SECURE_SSL_REDIRECT entra en bucle infinito.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=EN_PRODUCCION)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=EN_PRODUCCION)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=EN_PRODUCCION)

# HTTP Strict Transport Security.
#
# El navegador recuerda esta cabecera durante todo el max-age y se niega a
# hablar por HTTP con el dominio, así que un valor alto es difícil de
# revertir: si el certificado caduca, el sitio queda inaccesible hasta
# arreglarlo. Por eso se arranca en 1 hora.
#
# Cuando el HTTPS esté estable en producción, subir por pasos:
#   SECURE_HSTS_SECONDS=86400      (1 día)
#   SECURE_HSTS_SECONDS=2592000    (30 días)
#   SECURE_HSTS_SECONDS=31536000   (1 año, valor recomendado)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=3600 if EN_PRODUCCION else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=EN_PRODUCCION
)
# El preload es prácticamente irreversible (hay que pedir la baja en la lista
# de los navegadores y esperar meses). Se deja desactivado a propósito y solo
# debe activarse con el HSTS ya a un año y todos los subdominios en HTTPS.
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)

# Cabeceras defensivas adicionales.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # el CSRF se lee desde JS en algunos formularios

# security.W021 pide activar SECURE_HSTS_PRELOAD. No se activa a propósito:
# entrar en la lista de preload de los navegadores exige HSTS a un año, todos
# los subdominios por HTTPS, y darse de baja lleva meses. Es una decisión de
# infraestructura, no de código, y debe tomarse cuando se cumplan esas tres
# condiciones. Se silencia para que `check --deploy` quede limpio y cualquier
# aviso nuevo se vea de inmediato.
SILENCED_SYSTEM_CHECKS = ["security.W021"]
